### ISSUE TITLE
Bug in Hornet kill count

### ISSUE THREAD

**Issue by SuperChez** [NerfIrelia73/HKWordle#6]
On the search bar, when you go to the entries for Hornet Sentinel and Hornet Protector, it marks each of them as having a kill count of 2. The two fights with hornet are separate bosses, so this would imply that there are 4 possible kills. Probably just a small mistake in the flagging for each entry, but I thought I would leave a bug report.

**Comment by Chris-Is-Awesome** [comment]
It does this for any boss that has more than one journal entry. Crystal Guardian threw me off for that reason as that also shows 2 kills.

**Comment by SuperChez** [comment]
Oh, thanks. I didn't realize at the time that the Hunter's Journal was wonky for some bosses. Still kind of a strange thing to have in it though.
