### ISSUE TITLE
Aluba Area Should be 'Multiple' not 'Greenpath'

### ISSUE THREAD

**Issue by Transistorsis** [NerfIrelia73/HKWordle#7]
https://github.com/NerfIrelia73/HKWordle/blob/0d8260a9d549a04e105b5f476a69af72805bc6f5/src/assets/entries.json#L95

The Alubas can be found in both Greenpath and the Queen's Gardens as per the HK Wiki [here](https://hollowknight.fandom.com/wiki/Aluba)

**Comment by NerfIrelia73** [comment]
Fixed
