### ISSUE TITLE
Images Not Displaying - Firebase Quota Exceeded

### ISSUE THREAD

**Issue by mendelsimon** [NerfIrelia73/HKWordle#8]
All images are broken. Accessing the image `src` URL returns the following JSON:
```json
{
  "error": {
    "code": 402,
    "message": "Quota has been exceeded for this project. Please visit the Firebase pricing page to learn more."
  }
}
```

**Comment by NerfIrelia73** [comment]
I switched plans on Firebase yesterday to account for the increased traffic so pictures might have trouble loading for a little bit.  The issue should hopefully fix itself soon
